environment: development
chdir: /projects/romey
address: 127.0.0.1
port: 5000
pid: /projects/romey/tmp/thin.pid
rackup: /projects/romey/config.ru
log: /projects/romey/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 128
daemonize: true

