environment: development
chdir: /home/deploy/romeydev
address: 127.0.0.1
port: 4800
pid: /home/deploy/romeydev/current/tmp/pids/thin.pid
rackup: /home/deploy/romeydev/current/config.ru
log: /home/deploy/romeydev/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 128
daemonize: true

