environment: production
chdir: /home/romey/webapp/current
address: 127.0.0.1
user: romey
group: romey
port: 5000
pid: /home/romey/webapp/current/tmp/pids/thin.pid
rackup: /home/romey/webapp/current/config.ru
log: /home/romey/webapp/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 128
daemonize: true

